version: '4'

services:
  postgres:
    image: postgres:15-alpine3.20
    container_name: postgres-db
    ports:
      - "5432:5432"
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: challenge
      POSTGRES_DB: develop
      POSTGRES_USER: challenge
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
