version: '4'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=challenge_password
      - POSTGRES_USER=challenge
      - POSTGRES_DB=challenge